[package]
name = "minestuck_datapack_generator"
version = "0.1.1"
edition = "2021"
authors = ["mraof <mraof@mraof.com>"]

[dependencies]
iced = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
walkdir = "2"